# Generated by Django 4.0.3 on 2022-03-20 13:24

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rate',
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'Курс', 'verbose_name_plural': 'Курсы'},
        ),
        migrations.AlterModelOptions(
            name='coursesection',
            options={'verbose_name': 'Секция', 'verbose_name_plural': 'Секции'},
        ),
        migrations.AlterModelOptions(
            name='episode',
            options={'verbose_name': 'Эпизод', 'verbose_name_plural': 'Эпизоды'},
        ),
        migrations.AlterField(
            model_name='episode',
            name='file',
            field=cloudinary.models.CloudinaryField(max_length=255),
        ),
    ]
